# Generated by Django 2.0.6 on 2018-06-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_showreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showreview',
            name='rating',
        ),
    ]
