# Generated by Django 2.0.6 on 2018-07-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.DecimalField(blank=0.0, decimal_places=1, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('review', models.TextField()),
            ],
        ),
    ]
