# Generated by Django 2.0.6 on 2018-07-10 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showlist',
            name='rating',
        ),
    ]
