# Generated by Django 2.0.6 on 2018-06-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showreview',
            name='username',
            field=models.CharField(default='Anonymous', max_length=200),
            preserve_default=False,
        ),
    ]
