# Generated by Django 2.0.6 on 2018-07-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20180722_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
            preserve_default=False,
        ),
    ]
