# Generated by Django 2.0.6 on 2018-07-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('date_released', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('summary', models.TextField(max_length=1000)),
                ('display', models.TextField(blank='{% static %}', null=True)),
                ('rating', models.DecimalField(blank=0.0, decimal_places=1, max_digits=11, null=True)),
            ],
        ),
    ]
