# Generated by Django 2.0.6 on 2018-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tvshow',
        ),
        migrations.AddField(
            model_name='show',
            name='rating',
            field=models.DecimalField(blank=0.0, decimal_places=1, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='site',
            field=models.CharField(blank='Sorry, no sites to watch from yet!', max_length=200, null=True),
        ),
    ]
