# Generated by Django 2.0.6 on 2018-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('date_released', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('summary', models.TextField(max_length=1000)),
                ('fullcast', models.TextField()),
                ('role', models.TextField()),
                ('synopsis', models.TextField()),
                ('video', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tvshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('date_released', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('summary', models.TextField(max_length=1000)),
            ],
        ),
    ]
